#!/bin/bash

# mongod - Ass't for starting Homebrew-based mongod

start()
{
  echo -n $"Starting mongod: "
  launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
  RETVAL=$?
  echo
}

stop()
{
  echo -n $"Stopping mongod: "
  launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
  RETVAL=$?
  echo
}

restart () {
	stop
	start
}

RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  condrestart)
    [ -f /var/lock/subsys/mongod ] && restart || :
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload|condrestart}"
    RETVAL=1
esac

exit $RETVAL