#!/bin/bash

# nginx - Ass't for starting Homebrew-based nginx

start()
{
  echo -n $"Starting nginx: "
  launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist
  RETVAL=$?
  echo
}

stop()
{
  echo -n $"Stopping nginx: "
  launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist
  RETVAL=$?
  echo
}

restart () {
	stop
	start
}

RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    RETVAL=1
esac

exit $RETVAL
